# Generated by Django 4.2.5 on 2023-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('titulo', models.CharField(max_length=55)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('VA', 'Vacaciones'), ('FE', 'Feriado'), ('SS', 'Suspensión de actividades'), ('SP', 'Suspensión de actividades PM'), ('PL', 'Periodo Lectivo'), ('SE', 'Suspensión de evaluaciones'), ('CE', 'Ceremonia'), ('ED', 'EDDA'), ('EV', 'Evaluación'), ('AY', 'Ayudantías'), ('HA', 'Hito Académico'), ('SA', 'Secretaría Académica'), ('', 'OAI')], max_length=2)),
                ('segmento', models.CharField(choices=[('CU', 'Comunidad USM'), ('ES', 'Estudiante'), ('PR', 'Profesor'), ('JF', 'Jefe de Carrera')], max_length=2)),
            ],
        ),
    ]
